// Note: This is typically generated by protoc
// Here's a simplified version for your prototype

module.exports = {
  NodeInfo: class {
    constructor(id, address, port, storage) {
      this.id = id;
      this.address = address;
      this.port = port;
      this.storage = storage;
    }
  },
  
  StorageInfo: class {
    constructor(total, used, free) {
      this.total = total;
      this.used = used;
      this.free = free;
    }
  },
  
  FileAnnouncement: class {
    constructor(id, address, port, filename, size, chunks) {
      this.id = id;
      this.address = address;
      this.port = port;
      this.filename = filename;
      this.size = size;
      this.chunks = chunks || [];
    }
  },
  
  Chunk: class {
    constructor(index, size, hash) {
      this.index = index;
      this.size = size;
      this.hash = hash;
    }
  },
  
  Response: class {
    constructor(message) {
      this.message = message;
    }
  },
  
  AnnounceResponse: class {
    constructor(message, replicationNodes) {
      this.message = message;
      this.replicationNodes = replicationNodes || [];
    }
  }
};