// Note: This is typically generated by protoc
// Here's a simplified version for your prototype

const grpc = require('@grpc/grpc-js');

module.exports = {
  StorageController: {
    service: {
      RegisterNode: {
        path: '/cloud.StorageController/RegisterNode',
        requestStream: false,
        responseStream: false,
        requestSerialize: (request) => Buffer.from(JSON.stringify(request)),
        requestDeserialize: (buffer) => JSON.parse(buffer.toString()),
        responseSerialize: (response) => Buffer.from(JSON.stringify(response)),
        responseDeserialize: (buffer) => JSON.parse(buffer.toString())
      },
      Heartbeat: {
        path: '/cloud.StorageController/Heartbeat',
        requestStream: false,
        responseStream: false,
        requestSerialize: (request) => Buffer.from(JSON.stringify(request)),
        requestDeserialize: (buffer) => JSON.parse(buffer.toString()),
        responseSerialize: (response) => Buffer.from(JSON.stringify(response)),
        responseDeserialize: (buffer) => JSON.parse(buffer.toString())
      },
      AnnounceFile: {
        path: '/cloud.StorageController/AnnounceFile',
        requestStream: false,
        responseStream: false,
        requestSerialize: (request) => Buffer.from(JSON.stringify(request)),
        requestDeserialize: (buffer) => JSON.parse(buffer.toString()),
        responseSerialize: (response) => Buffer.from(JSON.stringify(response)),
        responseDeserialize: (buffer) => JSON.parse(buffer.toString())
      },
      GetFileLocations: {
        path: '/cloud.StorageController/GetFileLocations',
        requestStream: false,
        responseStream: false,
        requestSerialize: (request) => Buffer.from(JSON.stringify(request)),
        requestDeserialize: (buffer) => JSON.parse(buffer.toString()),
        responseSerialize: (response) => Buffer.from(JSON.stringify(response)),
        responseDeserialize: (buffer) => JSON.parse(buffer.toString())
      }
    },
    // Client constructor
    client: (address, credentials) => {
      const client = new grpc.Client(address, credentials);
      
      return {
        RegisterNode: (request, callback) => {
          const method = module.exports.StorageController.service.RegisterNode;
          const call = client.makeUnaryRequest(
            method.path,
            method.requestSerialize,
            method.responseDeserialize,
            request,
            callback
          );
          return call;
        },
        Heartbeat: (request, callback) => {
          const method = module.exports.StorageController.service.Heartbeat;
          const call = client.makeUnaryRequest(
            method.path,
            method.requestSerialize,
            method.responseDeserialize,
            request,
            callback
          );
          return call;
        },
        AnnounceFile: (request, callback) => {
          const method = module.exports.StorageController.service.AnnounceFile;
          const call = client.makeUnaryRequest(
            method.path,
            method.requestSerialize,
            method.responseDeserialize,
            request,
            callback
          );
          return call;
        },
        GetFileLocations: (request, callback) => {
          const method = module.exports.StorageController.service.GetFileLocations;
          const call = client.makeUnaryRequest(
            method.path,
            method.requestSerialize,
            method.responseDeserialize,
            request,
            callback
          );
          return call;
        }
      };
    }
  },
  
  NodeFileService: {
    service: {
      DownloadFile: {
        path: '/cloud.NodeFileService/DownloadFile',
        requestStream: false,
        responseStream: false,
        requestSerialize: (request) => Buffer.from(JSON.stringify(request)),
        requestDeserialize: (buffer) => JSON.parse(buffer.toString()),
        responseSerialize: (response) => Buffer.from(JSON.stringify(response)),
        responseDeserialize: (buffer) => JSON.parse(buffer.toString())
      },
      ReplicateFile: {
        path: '/cloud.NodeFileService/ReplicateFile',
        requestStream: false,
        responseStream: false,
        requestSerialize: (request) => Buffer.from(JSON.stringify(request)),
        requestDeserialize: (buffer) => JSON.parse(buffer.toString()),
        responseSerialize: (response) => Buffer.from(JSON.stringify(response)),
        responseDeserialize: (buffer) => JSON.parse(buffer.toString())
      }
    }
  }
};